name: Push Create-React-App Files to Webservices-Static

on:
  push:
    branches:
      - cra-test

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
      with:
        path: main

    - name: Navigate to repo
      run: cd $GITHUB_WORKSPACE
    - uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: Install deps
      run: cd main && yarn
    - name: Build docs
      run: cd main && yarn build

    - name: Checkout Receiving Repo
      uses: actions/checkout@v2
      with:
        repository: "BrownUniversity/webservices-static"
        path: reactapp
        token: ${{ secrets.WS_ACCESS_TEST }}

    - name: Copy existing Files
      run: cp -r main/build reactapp/src/demo/contrast-checker/build

    - name: Open Pull Request in WS-S
      id: pull-request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.WS_ACCESS_TEST }}
        path: reactapp
        commit-message: "Updated complied code for new C3 deployment"
        branch: contrast-checker-cra
        title: "Changes for WS-S deployment from Contrast Checker"
        body: "Changes from adam-at-brown/contrast-checker @rnorigian @adam-at-brown"
        labels: |
            test
            cra deploy
            github actions
        team-reviewers: |
          owners
          maintainers
        reviewers: |
          adam-at-brown
          rnorigian
